name: Temple of Gloom
run-name: ${{ github.workflow }} - ${{ github.run_number }}
#on: [pull_request]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: build project
        run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: test project
        run: make testAll
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: lint project
        run: make lint
