name: Temple of Gloom
run-name: ${{ github.workflow }} - ${{ github.run_number }}
#on: [pull_request]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - run: make testAll
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: make lint
